Sam071100/CodeForces-Solutions

- dfs
> basic algorithms

- odd_gcd.cpp
> CodeChef Problem: BININVER

- .vscode/settings.json
- a_cherry.cpp
- diwali1.cpp
link: https://codeforces.com/contest/1554/problem/A
> Codeforces Round #735 (Div. 2), problem: (A) Cherry

- EITA.cpp
I have added one codechef question solution.
Question link:https://www.codechef.com/problems/EITA
I hope you will like it.
Thank you.
> Added codechef EITA problem solution.

- Friends and the Restaurant.cpp
Codeforces Round #820 (Div. 3)
> Friends_and_the_Restaurant

- Sieve_of_Eratosthenes.cpp
Added code for sieve of erasthosthenes
> Added code for sieve of erasthosthenes

- Image.cpp
- sol.cpp
> Added sol for codeforces

- B. Prefix Sum Addicts
Added solution for B. Prefix Sum Addicts
> Added solution for B. Prefix Sum Addicts

- B. Array Recovery
Added solution of B. Added Recovery
> Added solution of B. Added Recovery

- C. Minimum Notation
Added solution to C. Minimum Notation
> Added solution to C. Minimum Notation

- .vscode/settings.json
- Cut_Ribbon.cpp
- Suppercentral_Point.ccp
- [165A - Super central Point](https://codeforces.com/problemset/problem/165/A)
- [189A -  Cut Ribbon](https://codeforces.com/problemset/problem/189/A)
> Add Supercentral Point - 165A & Cut Ribbon 189A

- vis_pull2.cpp
> created news solution for Round 825 B

- cpp4.cpp
successfully passed all the test cases of good subarray hard version
> solved D of round 825

- solved_cpp3.cpp
solved good subarray problem easy version
> Solved problem C of round 825

- EVMHACK@codechef.cpp
This is a CPP code regarding EVMHACK of code chef .
> EVMHACK@codechef.CPP

- template.cpp
Added Template for Competitive programming like codeforces
> Added Template for Competitive programming

- Sum_of_SubSet.cpp
The sum of Subarrays CodeForces solutions. Addresses this issue Add solutions to the Codeforces Problems #1
> Sum of Subarrays CodeForces solutions

- shortest_bridge.cpp
Addresses Add solutions to the Codeforces Problems #1
> Adding Construct Bride Codeforces Solutions

- cherry_pickup2.cpp
Addresses Issuse Add solutions to the Codeforces Problems #1
> Code For cherry Pickup 2 CodeForces

- A_Equal_or_Not_Equal.cpp
CodeForces Problem Link: https://codeforces.com/problemset/problem/1620/A
CodeForces Problem Number: 1620A
> added solution for CodeForces Problem Number: 1620A

- Chef_and_Instant_Noodles.cpp
Added solution to CodeChef problem 'Chef and Instant Noodles'
Link: https://www.codechef.com/practice/PCPP01/problems/INSTNOODLE
> added CodeChef problem Chef and Instant Noodles : PCPP01/INSTNOODLE

- A_Helpful_Maths.cpp
CodeForces Problem Link: https://codeforces.com/problemset/problem/339/A
Problem Number: 339A
> added solution for CodeForces Problem Number: 339A

- C__To_Become_Max.cpp
Problem Link : [Click Here](https://codeforces.com/contest/1856/problem/C)
(This is Problem 'C' from [Codeforces Round 890](https://codeforces.com/contest/1856))
> Uploaded solution of C : To Become Max

- To_find_keywords.c
- To_find_keywords.txt
Hey I want you to please add these two files in your repository as they contains program to find the number of keywords in a given text file.
> Program to find the number of keywords in a given text file !!!

- A_Remove_Smallest.cpp
CodeForces Problem Link: https://codeforces.com/problemset/problem/1399/A
CodeForces Problem Number: 1399A
> added the solution of CodeForces Problem Number: 1399A

- JellyfishandUndertale.cpp
CodeForces Problem Link: https://codeforces.com/contest/1875/problem/A
Problem Number: 1875A
> added solution for CodeForces Problem Number: 1875A
